HotelManagment/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hotel.DAO.HotelService;
using Hotel.DAO.PublicModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HotelManagment.Controllers
{
    public class GuestController : BaseController
    {
        private readonly IGuestService _guestService;

        public GuestController(IGuestService guestService,
            IWorkerSendEmailService workerSendEmailService): base(workerSendEmailService)
        {
            _guestService = guestService;
        }



        // GET: Guest
        public async Task<ActionResult> Index()
        {

            return View(await _guestService.GetQuestsAsync());
        }

        // GET: Guest/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Guest/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Guest/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Guest guest)
        {
            try
            {
                // TODO: Add insert logic here
                await _guestService.AddQuestAsync(guest);
                TempData["CRUDinfo"] = "Utworzono pomyślnie";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Guest/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            return View(await _guestService.FindGuestByIdAsync(id));
        }

        // POST: Guest/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, Guest guest)
        {
            try
            {
                // TODO: Add update logic here
                await _guestService.UpdateQuest(guest, id);
                TempData["CRUDinfo"] = "Zaktualizowano pomyślnie";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Guest/Delete/5
        public ActionResult Delete()
        {
            return View();
        }

        public ActionResult Sugestions(string term)
        {
            var pom = _guestService.FindGuestByName(term).Select(_ => new { label = $"{_.Name} {_.Surname} {_.Pesel}", ID = _.ID });
            pom = pom.Count() <= 0 ? pom.DefaultIfEmpty().Select(_ => new { label = "Nic nie znaleziono", ID = "" }).Take(1)
                : pom;
            return Json(pom);
        }

        // POST: Guest/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id)
        {
            try
            {
                // TODO: Add delete logic here
                await _guestService.DeleteQuestAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

HotelManagment/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hotel.DAO.HotelService;
using Hotel.DAO.PublicModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HotelManagment.Controllers
{
    public class ReservationController : BaseController
    {
        private readonly IRoomService _roomService;
        private readonly IGuestService _guestService;
        private readonly IReservationService _reservationService;
        private readonly IValidatorService _validatorService;

        public ReservationController(IRoomService roomService
            , IReservationService reservationService
            , IWorkerSendEmailService workerSendEmailService
            , IGuestService guestService
            , IValidatorService validatorService) : base(workerSendEmailService)
        {
            _roomService = roomService;
            _reservationService = reservationService;
            _guestService = guestService;
            _validatorService = validatorService;
        }

        // GET: Reservation
        public async Task<ActionResult> Index()
        {
            return View(await _reservationService.GetReservationsAsync());
        }

        // GET: Reservation/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }


        // GET: Reservation/Create
        public async Task<ActionResult> Create()
        {
            //ViewBag.Room = new SelectList(await _roomService.FindAvaiableRoomAsync(), "ID", "Category");

            List<SelectListItem> selectListItems = await RoomAvaiable();
            ViewBag.Room = selectListItems;
            return View();
        }

        private async Task<List<SelectListItem>> RoomAvaiable()
        {
            var pom = await _roomService.FindAvaiableRoomAsync();
            List<SelectListItem> selectListItems = new List<SelectListItem>();
            foreach (var item in pom)
            {
                SelectListItem selectListItem = new SelectListItem()
                {
                    Text =
                    $"Opis = {item.Description} | " +
                    $"Cena = {item.Amount} zł | " +
                    $"Kategoria = {item.Category.Category} | " +
                    $"Ilość osób = {item.Capacity}",
                    Value = item.ID
                };
                selectListItems.Add(selectListItem);

            }

            if (selectListItems.Count() == 0)
            {
                selectListItems.Add(new SelectListItem() { Text = "Brak wolnych pokoji" });
            }

            return selectListItems;
        }

        // POST: Reservation/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Reservation reservation)
        {
            try
            {
                ViewBag.NameGuest = reservation.GuestID;
                List<SelectListItem> selectListItems = await RoomAvaiable();
                ViewBag.Room = selectListItems;
                DateTime now = DateTime.Now;
                // TODO: Add insert logic here
                string[] buf = reservation.GuestID.Split(' ');
                var pesel = buf.Length >= 3 ? buf[2] : "";
                var guest = await _guestService.FindGuestByPeselAsync(pesel);
                if (guest == null)
                {
                    ViewBag.Error = $"Nie znaleziono takiego gościa";
                    return View();
                }
                else if (string.IsNullOrEmpty(reservation.Room)
                   || reservation.Room.IndexOf("Brak wolnych pokoji") > -1)
                {
                    ViewBag.Error = $"Brak wolnych pokoji";
                    return View();
                }
                else if (_validatorService.DateIsInValid(reservation, now))
                {
                    ViewBag.Error = $"Błędne daty";
                    return View();
                }
                else
                {

                    if (buf.Length < 3)
                    {
                        ViewBag.Error = $"Nie znaleziono takiego gościa";
                        return View();
                    }
                    else
                    {
                        var pom = await _guestService.FindGuestByPeselAsync(buf[2]);
                        var pom2 = await _roomService.FindRoomByIdAsync(reservation.Room);
                        reservation.GuestID = pom.ID;
                        reservation.Guest = pom;
                        reservation.Rooms = pom2;
                        await _reservationService.SaveReservationAsync(reservation);
                    }
                }

                TempData["CRUDinfo"] = "Utworzono pomyślnie";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Reservation/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            List<SelectListItem> selectListItems = await RoomAvaiable();
            ViewBag.Room = selectListItems;
            var pom = await _reservationService.FindReservationByIdAsync(id);
            return View(pom);
        }

        // POST: Reservation/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Reservation reservation, string id)
        {
            try
            {
                List<SelectListItem> selectListItems = await RoomAvaiable();
                ViewBag.Room = selectListItems;
                DateTime now = DateTime.Now;
                // TODO: Add insert logic here
                if (_validatorService.DateIsInValid(reservation, now)
                    && !reservation.IsConfirmed)
                {
                    ViewBag.Error = $"Błędne daty";
                    return View(reservation);
                }
                else
                {
                    var pom = await _guestService.FindGuestByIdAsync(reservation.GuestID);
                    var pom2 = await _roomService.FindRoomByIdAsync(reservation.Room);

                    if (pom2 == null)
                    {
                        ViewBag.Error = $"Wybrany pokój nie istnieje";
                        return View(reservation);
                    }
                    else
                    {
                        reservation.GuestID = pom.ID;
                        reservation.Guest = pom;
                        reservation.Rooms = pom2;
                        if (reservation.Unregister)
                        {
                            reservation.Price = _reservationService.CalculatePriceToPay(_validatorService.DateBetweenDays(reservation.FromDate, now), reservation.Rooms.Amount);
                        }
                        await _reservationService.UpdateReservationAsync(reservation, id);
                        TempData["CRUDinfo"] = "Zaktualizowno pomyślnie";
                    }
                }

            }
            catch
            {
                ViewBag.Error = $"Zostały wybrane błędne dane";
                return View(await _reservationService.FindReservationByIdAsync(id));
            }

            // TODO walidacja daty
            // TODO: Add update logic here               
            return RedirectToAction(nameof(Index));
        }


        // GET: Reservation/Delete/5
        public ActionResult Delete()
        {
            return View();
        }

        // POST: Reservation/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id)
        {
            try
            {
                // TODO: Add delete logic here
                await _reservationService.ReservationDelete(id);
                TempData["CRUDinfo"] = "Skasowno pomyślnie";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

HotelManagment/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hotel.DAO.HotelService;
using Hotel.DAO.PublicModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HotelManagment.Controllers
{
    public class RoomController : BaseController
    {
        private readonly IRoomService _romService;
        private readonly IRoomStatusService _roomStatusService;
        private readonly IRoomCateggoryService _roomCateggory;
        private readonly IReservationService _reservationService; 

        public RoomController(IRoomService romService
            , IRoomStatusService roomStatusService
            , IWorkerSendEmailService workerSendEmail
            , IRoomCateggoryService roomCateggory
            , IReservationService reservationService) : base(workerSendEmail)
        {
            _romService = romService;
            _roomStatusService = roomStatusService;
            _roomCateggory = roomCateggory;
            _reservationService = reservationService;

        }

        // GET: Room
        public async Task<ActionResult> Index()
        {
            return View(await _romService.GetRoomsAsync());
        }

        // GET: Room/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Room/Create
        public async Task<ActionResult> Create()
        {
            await StatusRoom();
            await CattegoryRoom();
            return View();
        }

        // POST: Room/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(include: "Amount,Capacity,Description,RoomNr,Status,Category")] Room room)
        {
            try
            {
                // TODO: Add insert logic here
                await _romService.AddRoomAsync(room);
                TempData["CRUDinfo"] = "Utworzono pomyślnie";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Room/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            await StatusRoom();
            await CattegoryRoom();
            return View(await _romService.FindRoomByIdAsync(id));
        }

        private async Task<dynamic> StatusRoom()
        {
            return ViewBag.Status = new SelectList(await _roomStatusService.GetStatusesAsync(), "Available", "Available");
        }

        private async Task<dynamic> CattegoryRoom()
        {
            return ViewBag.Cattegory = new SelectList(await _roomCateggory.GetRoomCateggoriesAsync(), "Category", "Category");
        }

        // POST: Room/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, [Bind(include: "ID,Amount,Capacity,Description,RoomNr,Status,Category")] Room room)
        {
            try
            {
                await StatusRoom();
                await CattegoryRoom();
                // TODO: Add update logic here
                TempData["CRUDinfo"] = "Zaktualizowano pomyślnie";
                await _romService.UpdateRoomAsync(room, id);
                await _reservationService.UpdateRoomInReservation(room.ID, room);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Room/Delete/5
        public ActionResult Delete()
        {
            return View();
        }

        // POST: Room/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id)
        {
            try
            {
                // TODO: Add delete logic here
                await _romService.DeleteRoomAsync(id);
                TempData["CRUDinfo"] = "Skasowno pomyślnie";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

HotelManagment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelManagment</title>
    <environment include="Development">
        <link href="~/lib/bootswatch/materia/bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/bootswatch/minty/bootstrap.min.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link href="~/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/jqueryui/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/jqueryui/jquery-ui.theme.min.css" rel="stylesheet" />
    <link href="~/lib/jquery-datetimepicker/jquery.datetimepicker.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/MyCss.min.css" rel="stylesheet" />
    @if (IsSectionDefined("MyCustomStyle"))
    {
        @RenderSection("MyCustomStyle", required: false)
    }
</head>
<body>

    <!--main page loader-->
    <div class="main-loader">
        <i class="fa fa-spin fa-spinner" aria-hidden="true"></i>
    </div>
    <!--end main page loader-->

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HotelManagment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="Index">Pokoje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Guest" asp-action="Index">Goście</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Rezerwacje</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div id="toTopPage">
        <i class="fa fa-arrow-up" aria-hidden="true"></i>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - HotelManagment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>

    <!-- Include Bootstrap Datepicker -->
    <script src="~/jqueryui/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
    <script src="~/lib/jquery-datetimepicker/jquery.datetimepicker.full.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

HotelManagment/Views/Shared/_SearchForm.cshtml
<div class="search-container">
    <input type="text" id="searchInput" class="form-control" placeholder="@Model" />
    <i class="fa fa-times remove-text-icon" aria-hidden="true"></i>
</div>

HotelManagment/Views/Shared/_ServerResponseInfo.cshtml
@if (TempData["CRUDinfo"] != null)
{
    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @TempData["CRUDinfo"]
    </div>
}